spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      mode: always
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 3001
  error:
    whitelabel:
      enabled: false

jwt:
  token:
    validity:
      access-token: 18000 #5 hours
      refresh-token: 31536000 #1 year
    prefix: Bearer
  header:
    string: Authorization
