version: '3.5'

services:
  postgres:
    container_name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
    - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    depends_on:
    - postgres
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - 5555:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge